/cluster/courses/machine_perception/project2/project2_venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py:563: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
torch.Size([2, 512, 1])
2024-06-10 15:44:37,566|    INFO| STEP 0 - EPOCH 0/2520 | total loss: 6.293E-01 | rgb loss: 6.293E-01
torch.Size([2, 512, 1])
torch.Size([2, 512, 1])
torch.Size([2, 512, 1])
torch.Size([2, 512, 1])
torch.Size([2, 512, 1])
torch.Size([2, 512, 1])
torch.Size([1, 512, 1])
2024-06-10 15:44:40,796|    INFO| Saving model checkpoint to: checkpoints/mp-2024/20240610-154423/fine_model-0.pth
/cluster/courses/machine_perception/project2/project2_venv/lib/python3.10/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2024-06-10 15:44:41,023|    INFO| Beginning validation...
2024-06-10 15:44:41,024|    INFO| Loaded validation dataset with 5 images at resolution 256x256
2024-06-10 15:44:41,025|    INFO| Saving reconstruction result to checkpoints/mp-2024/20240610-154423/mesh
torch.Size([1, 10240, 1])
  0%|                                                                                               | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/georye/project2/train.py", line 157, in <module>
    main(args)
  File "/home/georye/project2/train.py", line 140, in main
    trainer.validate(valid_loader, rander_shape, step=global_step, epoch=epoch,
  File "/home/georye/project2/lib/model/trainer.py", line 390, in validate
    ray_rgb, ray_depth, ray_alpha = self.render(ray_orig, ray_dir)
  File "/home/georye/project2/lib/model/trainer.py", line 289, in render
    coords, depth, deltas, _ = self.sample_points(ray_orig, ray_dir, near=self.cfg.near, far=self.cfg.far,
ValueError: too many values to unpack (expected 4)